### ISSUE TITLE
sdb dlog command does not work with Tizen 5.5

### ISSUE THREAD

**Issue by aril-spetalen** [TizenTeam/sdb#1]
*Problem*
I am not able to read logs from my smart-TV with sdb.

According to this docoumentation: https://developer.tizen.org/dev-guide/2.4/org.tizen.devtools/html/common_tools/smart_dev_bridge.htm#log, it should be possible to call something a la 

'sdb -s <deviceId> dlog *:V' 

to retrieve verbose logs from all applications.
I get no output from this. I am able to debug the app, forward ports and more, but I cannot get logs this way. 

Could it be, no applications log anything at all? (Seems not likely to me). 
Have I misunderstood the syntax?
Is there an issue with sdb dlog?

I am testing with a 2020 standard Tizen 5.5 TV, model QE50Q60TAUXXC. Connecting from a debian linux computer.

**Comment by rzr** [comment]
Maybe this should be forwarded to Samsung TV forums

**Comment by MacgyverMartins** [comment]
I am having the same problem. Actually I can not use any of the sdb commands on my tv or emulator.
There is some place where we can find the correctly information about how to use sdb ? Because I had problems to run all the commands I saw in your documentations.
 `~/tizen-studio/tools/sdb shell` returns `closed`
 `~/tizen-studio/tools/sdb dlog` also returns `close`
 
I don't find answers to any off my questions on Sumsumg Forum.
Can someone please tell me why this happens?

**Comment by mirh** [comment]
This repo is very much dead. 
You can find something slightly newer [here](https://review.tizen.org/git/?p=sdk/tools/sdb.git) then, but every recent OS/device release is probably gonna require the [binary releases](https://download.tizen.org/sdk/tizenstudio/official/binary/sdb_4.2.25_ubuntu-64.zip).

**Comment by rzr** [comment]
Is there any recent git tree available anywhere ?

**Comment by aril-spetalen** [comment]
I'm out of the samsung app business, and this issue seems not to have got any attention. I'll close. For those interested, pls. refer to mirh's links in the recent comments above.
